config/routes.rb
Rails.application.routes.draw do
  resources :libros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "libros#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @q = Libro.ransack(params[:q])
    @libros = @q.result(distinct: true)
   #@libros = Libro.page(params[:page])

  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:title, :author, :state, :lended_at, :returned_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Titulo %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Autor %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :Prestado %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :Prestado_el %>
    <%= form.date_select :lended_at %>
  </div>

  <div class="field">
    <%= form.label :Devuelto_el%>
    <%= form.date_select :returned_at, {:prompt => "No devuelto"}  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editar Libro prestado</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tu biblioteca</h1>

 <%= search_form_for @q do |f| %>
  <%= f.label :state %>
  <%= f.select :state_eq, options_for_select([:true, :false])%>
  <%= f.submit %>


  <% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :title) %></th>
      <th>Autor</th>
      <th>Prestado</th>
      <th>Prestado el</th>
      <th>Devuelto el</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.title %></td>
        <td><%= libro.author %></td>
        <td><%= libro.state %></td>
        <td><%= libro.lended_at %></td>
        <td><%= libro.returned_at %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Seguro que quieres Borrar' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>Nuevo Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @libro.title %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.author %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @libro.state %>
</p>

<p>
  <strong>Prestado el:</strong>
  <%= @libro.lended_at %>
</p>

<p>
  <strong>Devuelto el:</strong>
  <%= @libro.returned_at %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>